-- Seed: insertion de tous les pays d'Afrique
-- Basé sur la liste des États membres de l'Union africaine + Sahara occidental

INSERT INTO public.countries
  (code, name_fr, name_en, region, continent, latitude, longitude, capital_city, official_language, working_languages, sutel_community)
VALUES
  ('DZ', 'Algérie', 'Algeria', 'Afrique du Nord', 'Afrique', 28.0339, 1.6596, 'Alger', 'ar', ARRAY['ar','fr'], NULL),
  ('AO', 'Angola', 'Angola', 'Afrique centrale', 'Afrique', -11.2027, 17.8739, 'Luanda', 'pt', ARRAY['pt'], NULL),
  ('BJ', 'Bénin', 'Benin', 'Afrique de l''Ouest', 'Afrique', 9.3077, 2.3158, 'Porto-Novo', 'fr', ARRAY['fr'], NULL),
  ('BW', 'Botswana', 'Botswana', 'Afrique australe', 'Afrique', -22.3285, 24.6849, 'Gaborone', 'en', ARRAY['en'], NULL),
  ('BF', 'Burkina Faso', 'Burkina Faso', 'Afrique de l''Ouest', 'Afrique', 12.2383, -1.5616, 'Ouagadougou', 'fr', ARRAY['fr'], NULL),
  ('BI', 'Burundi', 'Burundi', 'Afrique de l''Est', 'Afrique', -3.3731, 29.9189, 'Gitega', 'rn', ARRAY['rn','fr'], NULL),
  ('CM', 'Cameroun', 'Cameroon', 'Afrique centrale', 'Afrique', 7.3697, 12.3547, 'Yaoundé', 'fr', ARRAY['fr','en'], NULL),
  ('CV', 'Cap-Vert', 'Cape Verde', 'Afrique de l''Ouest', 'Afrique', 16.5388, -23.0418, 'Praia', 'pt', ARRAY['pt'], NULL),
  ('CF', 'République centrafricaine', 'Central African Republic', 'Afrique centrale', 'Afrique', 6.6111, 20.9394, 'Bangui', 'fr', ARRAY['fr'], NULL),
  ('TD', 'Tchad', 'Chad', 'Afrique centrale', 'Afrique', 15.4542, 18.7322, 'N''Djaména', 'fr', ARRAY['fr','ar'], NULL),
  ('KM', 'Comores', 'Comoros', 'Afrique de l''Est', 'Afrique', -11.8750, 43.8722, 'Moroni', 'ar', ARRAY['ar','fr'], NULL),
  ('CG', 'Congo', 'Congo', 'Afrique centrale', 'Afrique', -0.2280, 15.8277, 'Brazzaville', 'fr', ARRAY['fr'], NULL),
  ('CD', 'République démocratique du Congo', 'Democratic Republic of the Congo', 'Afrique centrale', 'Afrique', -4.0383, 21.7587, 'Kinshasa', 'fr', ARRAY['fr'], NULL),
  ('CI', 'Côte d''Ivoire', 'Ivory Coast', 'Afrique de l''Ouest', 'Afrique', 7.5400, -5.5471, 'Yamoussoukro', 'fr', ARRAY['fr'], NULL),
  ('DJ', 'Djibouti', 'Djibouti', 'Afrique de l''Est', 'Afrique', 11.8251, 42.5903, 'Djibouti', 'fr', ARRAY['fr','ar'], NULL),
  ('EG', 'Égypte', 'Egypt', 'Afrique du Nord', 'Afrique', 26.8206, 30.8025, 'Le Caire', 'ar', ARRAY['ar'], NULL),
  ('GQ', 'Guinée équatoriale', 'Equatorial Guinea', 'Afrique centrale', 'Afrique', 1.6508, 10.2679, 'Malabo', 'es', ARRAY['es','fr'], NULL),
  ('ER', 'Érythrée', 'Eritrea', 'Afrique de l''Est', 'Afrique', 15.1794, 39.7823, 'Asmara', 'ti', ARRAY['ti','ar','en'], NULL),
  ('SZ', 'Eswatini', 'Eswatini', 'Afrique australe', 'Afrique', -26.5225, 31.4659, 'Mbabane', 'en', ARRAY['en','ss'], NULL),
  ('ET', 'Éthiopie', 'Ethiopia', 'Afrique de l''Est', 'Afrique', 9.1450, 40.4897, 'Addis-Abeba', 'am', ARRAY['am'], NULL),
  ('GA', 'Gabon', 'Gabon', 'Afrique centrale', 'Afrique', -0.8037, 11.6094, 'Libreville', 'fr', ARRAY['fr'], NULL),
  ('GM', 'Gambie', 'Gambia', 'Afrique de l''Ouest', 'Afrique', 13.4432, -15.3101, 'Banjul', 'en', ARRAY['en'], NULL),
  ('GH', 'Ghana', 'Ghana', 'Afrique de l''Ouest', 'Afrique', 7.9465, -1.0232, 'Accra', 'en', ARRAY['en'], NULL),
  ('GN', 'Guinée', 'Guinea', 'Afrique de l''Ouest', 'Afrique', 9.9456, -9.6966, 'Conakry', 'fr', ARRAY['fr'], NULL),
  ('GW', 'Guinée-Bissau', 'Guinea-Bissau', 'Afrique de l''Ouest', 'Afrique', 11.8037, -15.1804, 'Bissau', 'pt', ARRAY['pt'], NULL),
  ('KE', 'Kenya', 'Kenya', 'Afrique de l''Est', 'Afrique', -0.0236, 37.9062, 'Nairobi', 'en', ARRAY['en','sw'], NULL),
  ('LS', 'Lesotho', 'Lesotho', 'Afrique australe', 'Afrique', -29.6100, 28.2336, 'Maseru', 'en', ARRAY['en','st'], NULL),
  ('LR', 'Libéria', 'Liberia', 'Afrique de l''Ouest', 'Afrique', 6.4281, -9.4295, 'Monrovia', 'en', ARRAY['en'], NULL),
  ('LY', 'Libye', 'Libya', 'Afrique du Nord', 'Afrique', 26.3351, 17.2283, 'Tripoli', 'ar', ARRAY['ar'], NULL),
  ('MG', 'Madagascar', 'Madagascar', 'Afrique de l''Est', 'Afrique', -18.7669, 46.8691, 'Antananarivo', 'mg', ARRAY['mg','fr'], NULL),
  ('MW', 'Malawi', 'Malawi', 'Afrique australe', 'Afrique', -13.2543, 34.3015, 'Lilongwe', 'en', ARRAY['en','ny'], NULL),
  ('ML', 'Mali', 'Mali', 'Afrique de l''Ouest', 'Afrique', 17.5707, -3.9962, 'Bamako', 'fr', ARRAY['fr'], NULL),
  ('MR', 'Mauritanie', 'Mauritania', 'Afrique de l''Ouest', 'Afrique', 21.0079, -10.9408, 'Nouakchott', 'ar', ARRAY['ar','fr'], NULL),
  ('MU', 'Maurice', 'Mauritius', 'Afrique de l''Est', 'Afrique', -20.3484, 57.5522, 'Port-Louis', 'en', ARRAY['en','fr'], NULL),
  ('MA', 'Maroc', 'Morocco', 'Afrique du Nord', 'Afrique', 31.7917, -7.0926, 'Rabat', 'ar', ARRAY['ar','fr'], NULL),
  ('MZ', 'Mozambique', 'Mozambique', 'Afrique australe', 'Afrique', -18.6657, 35.5296, 'Maputo', 'pt', ARRAY['pt'], NULL),
  ('NA', 'Namibie', 'Namibia', 'Afrique australe', 'Afrique', -22.9576, 18.4904, 'Windhoek', 'en', ARRAY['en'], NULL),
  ('NE', 'Niger', 'Niger', 'Afrique de l''Ouest', 'Afrique', 17.6078, 8.0817, 'Niamey', 'fr', ARRAY['fr'], NULL),
  ('NG', 'Nigeria', 'Nigeria', 'Afrique de l''Ouest', 'Afrique', 9.0820, 8.6753, 'Abuja', 'en', ARRAY['en'], NULL),
  ('RW', 'Rwanda', 'Rwanda', 'Afrique de l''Est', 'Afrique', -1.9403, 29.8739, 'Kigali', 'rw', ARRAY['rw','fr','en'], NULL),
  ('ST', 'Sao Tomé-et-Principe', 'Sao Tome and Principe', 'Afrique centrale', 'Afrique', 0.1864, 6.6131, 'São Tomé', 'pt', ARRAY['pt'], NULL),
  ('SN', 'Sénégal', 'Senegal', 'Afrique de l''Ouest', 'Afrique', 14.4974, -14.4524, 'Dakar', 'fr', ARRAY['fr'], NULL),
  ('SC', 'Seychelles', 'Seychelles', 'Afrique de l''Est', 'Afrique', -4.6796, 55.4920, 'Victoria', 'fr', ARRAY['fr','en'], NULL),
  ('SL', 'Sierra Leone', 'Sierra Leone', 'Afrique de l''Ouest', 'Afrique', 8.4606, -11.7799, 'Freetown', 'en', ARRAY['en'], NULL),
  ('SO', 'Somalie', 'Somalia', 'Afrique de l''Est', 'Afrique', 5.1521, 46.1996, 'Mogadiscio', 'so', ARRAY['so','ar'], NULL),
  ('ZA', 'Afrique du Sud', 'South Africa', 'Afrique australe', 'Afrique', -30.5595, 22.9375, 'Pretoria', 'af', ARRAY['af','en','zu','xh',...], NULL),
  ('SS', 'Soudan du Sud', 'South Sudan', 'Afrique de l''Est', 'Afrique', 6.8770, 31.3070, 'Djouba', 'en', ARRAY['en'], NULL),
  ('SD', 'Soudan', 'Sudan', 'Afrique du Nord', 'Afrique', 12.8628, 30.2176, 'Khartoum', 'ar', ARRAY['ar','en'], NULL),
  ('TZ', 'Tanzanie', 'Tanzania', 'Afrique de l''Est', 'Afrique', -6.3690, 34.8888, 'Dodoma', 'sw', ARRAY['sw','en'], NULL),
  ('TG', 'Togo', 'Togo', 'Afrique de l''Ouest', 'Afrique', 8.6195, 0.8248, 'Lomé', 'fr', ARRAY['fr'], NULL),
  ('TN', 'Tunisie', 'Tunisia', 'Afrique du Nord', 'Afrique', 33.8869, 9.5375, 'Tunis', 'ar', ARRAY['ar','fr'], NULL),
  ('UG', 'Ouganda', 'Uganda', 'Afrique de l''Est', 'Afrique', 1.3733, 32.2903, 'Kampala', 'en', ARRAY['en','sw'], NULL),
  ('EH', 'Sahara occidental', 'Western Sahara', 'Afrique du Nord', 'Afrique', 24.2155, -12.8858, 'Laâyoune', 'ar', ARRAY['ar','es'], NULL),
  ('ZM', 'Zambie', 'Zambia', 'Afrique australe', 'Afrique', -13.1339, 27.8493, 'Lusaka', 'en', ARRAY['en'], NULL),
  ('ZW', 'Zimbabwe', 'Zimbabwe', 'Afrique australe', 'Afrique', -19.0154, 29.1549, 'Harare', 'en', ARRAY['en','sn','nd'], NULL);

-- Note : Pour l'Afrique du Sud (ZA), les langues officielles sont nombreuses (11). Nous avons mis un exemple simplifié.
-- Les colonnes `official_language` et `working_languages` peuvent être ajustées selon vos besoins précis.