export interface CrossBorderProject {
  id: string;
  title: string;
  description: string;
  partner_countries: string[];
  theme: string;
  status: string;
  budget: number | null;
  beneficiaries: number | null;
  completion_percentage: number;
  start_date: string | null;
  end_date: string | null;
}

export const DEMO_PROJECTS: CrossBorderProject[] = [
  {
    id: "cb-1",
    title: "Dorsale fibre optique Abidjan-Accra",
    description: "Interconnexion haut débit entre la Côte d'Ivoire et le Ghana pour réduire les coûts de transit régional.",
    partner_countries: ["Côte d'Ivoire", "Ghana"],
    theme: "connectivity",
    status: "active",
    budget: 12_500_000,
    beneficiaries: 850_000,
    completion_percentage: 64,
    start_date: "2024-03-01",
    end_date: "2026-06-30",
  },
  {
    id: "cb-2",
    title: "Programme scolaire numérique CEDEAO",
    description: "Déploiement de tablettes éducatives et contenus pédagogiques multilingues dans 500 écoles.",
    partner_countries: ["Sénégal", "Mali", "Burkina Faso"],
    theme: "education",
    status: "active",
    budget: 8_200_000,
    beneficiaries: 125_000,
    completion_percentage: 42,
    start_date: "2024-09-01",
    end_date: "2027-08-31",
  },
  {
    id: "cb-3",
    title: "Corridor numérique de santé Est-africain",
    description: "Télémédecine et dossiers médicaux électroniques partagés entre trois pays d'Afrique de l'Est.",
    partner_countries: ["Kenya", "Tanzanie", "Ouganda"],
    theme: "health",
    status: "active",
    budget: 15_000_000,
    beneficiaries: 2_300_000,
    completion_percentage: 35,
    start_date: "2025-01-15",
    end_date: "2028-01-14",
  },
  {
    id: "cb-4",
    title: "Réseau AgriData Sahel",
    description: "Plateforme de données agricoles en temps réel pour l'aide à la décision des agriculteurs sahéliens.",
    partner_countries: ["Niger", "Mali", "Burkina Faso"],
    theme: "agriculture",
    status: "planned",
    budget: 5_600_000,
    beneficiaries: 340_000,
    completion_percentage: 10,
    start_date: "2026-01-01",
    end_date: "2028-12-31",
  },
  {
    id: "cb-5",
    title: "e-Gouvernance côtière UEMOA",
    description: "Harmonisation des plateformes de services publics numériques entre les pays côtiers de l'UEMOA.",
    partner_countries: ["Togo", "Bénin", "Côte d'Ivoire"],
    theme: "governance",
    status: "active",
    budget: 7_800_000,
    beneficiaries: 1_500_000,
    completion_percentage: 55,
    start_date: "2024-06-01",
    end_date: "2026-12-31",
  },
  {
    id: "cb-6",
    title: "Smart Campus Grands Lacs",
    description: "Réseau de campus universitaires connectés avec partage de cours à distance entre les universités.",
    partner_countries: ["RDC", "Rwanda", "Ouganda"],
    theme: "education",
    status: "planned",
    budget: 4_200_000,
    beneficiaries: 45_000,
    completion_percentage: 5,
    start_date: "2026-09-01",
    end_date: "2029-06-30",
  },
  {
    id: "cb-7",
    title: "Backbone 5G Cameroun-Niger",
    description: "Extension du réseau 5G pilote avec partage d'infrastructure entre opérateurs des deux pays.",
    partner_countries: ["Cameroun", "Niger"],
    theme: "connectivity",
    status: "completed",
    budget: 22_000_000,
    beneficiaries: 3_100_000,
    completion_percentage: 100,
    start_date: "2023-01-01",
    end_date: "2025-06-30",
  },
  {
    id: "cb-8",
    title: "Observatoire régional de cybersécurité",
    description: "Centre de veille et réponse aux incidents cyber partagé entre 4 pays de l'Afrique de l'Ouest.",
    partner_countries: ["Sénégal", "Côte d'Ivoire", "Ghana", "Cameroun"],
    theme: "governance",
    status: "active",
    budget: 9_400_000,
    beneficiaries: 0,
    completion_percentage: 72,
    start_date: "2024-01-01",
    end_date: "2026-12-31",
  },
  {
    id: "cb-9",
    title: "Telesanté Maternelle Madagascar-Kenya",
    description: "Programme de suivi prénatal à distance connectant des cliniques rurales via satellite.",
    partner_countries: ["Madagascar", "Kenya"],
    theme: "health",
    status: "active",
    budget: 3_500_000,
    beneficiaries: 180_000,
    completion_percentage: 48,
    start_date: "2024-07-01",
    end_date: "2026-06-30",
  },
  {
    id: "cb-10",
    title: "Identité numérique transfrontalière EAC",
    description: "Système d'identité numérique interopérable pour faciliter la mobilité dans la Communauté Est-Africaine.",
    partner_countries: ["Kenya", "Tanzanie", "Rwanda", "Ouganda"],
    theme: "governance",
    status: "planned",
    budget: 18_000_000,
    beneficiaries: 5_000_000,
    completion_percentage: 8,
    start_date: "2026-06-01",
    end_date: "2029-12-31",
  },
];
