-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.agencies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  acronym text NOT NULL UNIQUE,
  country text NOT NULL,
  region text NOT NULL CHECK (region = ANY (ARRAY['CEDEAO'::text, 'SADC'::text, 'EACO'::text, 'ECCAS'::text, 'UMA'::text])),
  website_url text NOT NULL,
  api_endpoint text,
  logo_url text,
  description text,
  contact_email text,
  phone text,
  address text,
  established_date date,
  is_active boolean DEFAULT true,
  last_sync_at timestamp with time zone,
  sync_status text DEFAULT 'pending'::text CHECK (sync_status = ANY (ARRAY['pending'::text, 'active'::text, 'error'::text, 'inactive'::text])),
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agencies_pkey PRIMARY KEY (id)
);
CREATE TABLE public.agency_connectors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agency_id uuid NOT NULL,
  connector_type text NOT NULL CHECK (connector_type = ANY (ARRAY['api'::text, 'scraper'::text, 'rss'::text, 'manual'::text])),
  endpoint_url text,
  auth_method text CHECK (auth_method = ANY (ARRAY['none'::text, 'api_key'::text, 'oauth'::text, 'basic'::text])),
  auth_config jsonb DEFAULT '{}'::jsonb,
  sync_frequency integer DEFAULT 3600,
  last_sync_at timestamp with time zone,
  sync_status text DEFAULT 'inactive'::text CHECK (sync_status = ANY (ARRAY['active'::text, 'error'::text, 'inactive'::text])),
  error_message text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agency_connectors_pkey PRIMARY KEY (id),
  CONSTRAINT agency_connectors_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES public.agencies(id)
);
CREATE TABLE public.agency_projects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agency_id uuid NOT NULL,
  external_id text,
  title text NOT NULL,
  description text,
  status text NOT NULL,
  budget numeric,
  beneficiaries integer,
  start_date date,
  end_date date,
  completion_percentage integer DEFAULT 0 CHECK (completion_percentage >= 0 AND completion_percentage <= 100),
  tags ARRAY,
  location text,
  coordinates point,
  source_url text,
  last_updated_at timestamp with time zone,
  sync_status text DEFAULT 'synced'::text CHECK (sync_status = ANY (ARRAY['synced'::text, 'modified'::text, 'conflict'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agency_projects_pkey PRIMARY KEY (id),
  CONSTRAINT agency_projects_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES public.agencies(id)
);
CREATE TABLE public.agency_resource_comments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  resource_id uuid NOT NULL,
  user_id uuid NOT NULL,
  user_name text NOT NULL,
  comment text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agency_resource_comments_pkey PRIMARY KEY (id),
  CONSTRAINT agency_resource_comments_resource_id_fkey FOREIGN KEY (resource_id) REFERENCES public.agency_resources(id),
  CONSTRAINT agency_resource_comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.agency_resource_versions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  resource_id uuid NOT NULL,
  version text NOT NULL,
  file_url text NOT NULL,
  file_name text NOT NULL,
  file_size bigint,
  changes_summary text NOT NULL,
  uploaded_by uuid NOT NULL,
  uploaded_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agency_resource_versions_pkey PRIMARY KEY (id),
  CONSTRAINT agency_resource_versions_resource_id_fkey FOREIGN KEY (resource_id) REFERENCES public.agency_resources(id),
  CONSTRAINT agency_resource_versions_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id)
);
CREATE TABLE public.agency_resources (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agency_id uuid NOT NULL,
  external_id text,
  title text NOT NULL,
  description text,
  resource_type text NOT NULL CHECK (resource_type = ANY (ARRAY['document'::text, 'guide'::text, 'report'::text, 'template'::text, 'tool'::text, 'other'::text])),
  file_url text,
  file_size bigint,
  mime_type text,
  tags ARRAY,
  download_count integer DEFAULT 0,
  source_url text,
  last_updated_at timestamp with time zone,
  sync_status text DEFAULT 'synced'::text CHECK (sync_status = ANY (ARRAY['synced'::text, 'modified'::text, 'conflict'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  access_level text NOT NULL DEFAULT 'public'::text,
  allowed_roles ARRAY DEFAULT '{}'::text[],
  shared_with_agencies ARRAY DEFAULT '{}'::uuid[],
  uploaded_by uuid,
  is_public boolean NOT NULL DEFAULT true,
  current_version text DEFAULT '1.0'::text,
  CONSTRAINT agency_resources_pkey PRIMARY KEY (id),
  CONSTRAINT agency_resources_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES public.agencies(id),
  CONSTRAINT agency_resources_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id)
);
CREATE TABLE public.anomaly_alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['suspicious_login'::text, 'unusual_location'::text, 'multiple_failures'::text, 'device_change'::text, 'time_anomaly'::text])),
  severity text NOT NULL DEFAULT 'medium'::text CHECK (severity = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  message text NOT NULL,
  details jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  resolved boolean DEFAULT false,
  auto_blocked boolean DEFAULT false,
  resolved_at timestamp with time zone,
  resolved_by uuid,
  CONSTRAINT anomaly_alerts_pkey PRIMARY KEY (id),
  CONSTRAINT anomaly_alerts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT anomaly_alerts_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.anomaly_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  location_monitoring boolean DEFAULT true,
  device_monitoring boolean DEFAULT true,
  time_pattern_monitoring boolean DEFAULT true,
  failed_login_threshold integer DEFAULT 5 CHECK (failed_login_threshold > 0),
  auto_block_enabled boolean DEFAULT false,
  sensitivity_level text DEFAULT 'medium'::text CHECK (sensitivity_level = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT anomaly_settings_pkey PRIMARY KEY (id),
  CONSTRAINT anomaly_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  action_type text NOT NULL,
  resource_type text,
  resource_id text,
  details jsonb,
  ip_address inet,
  user_agent text,
  success boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.compliance_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  report_type text NOT NULL CHECK (report_type = ANY (ARRAY['gdpr'::text, 'hipaa'::text, 'sox'::text, 'iso27001'::text, 'custom'::text])),
  title text NOT NULL,
  description text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'in_progress'::text, 'completed'::text, 'failed'::text])),
  report_data jsonb,
  file_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  scheduled_for timestamp with time zone,
  CONSTRAINT compliance_reports_pkey PRIMARY KEY (id),
  CONSTRAINT compliance_reports_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.countries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name_fr text NOT NULL,
  name_en text NOT NULL,
  region text,
  continent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  latitude numeric,
  longitude numeric,
  capital_city text,
  official_language text DEFAULT 'fr'::text,
  working_languages ARRAY DEFAULT ARRAY['fr'::text],
  sutel_community text,
  CONSTRAINT countries_pkey PRIMARY KEY (id)
);
CREATE TABLE public.data_sources (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  acronym text NOT NULL,
  description text,
  website_url text,
  api_endpoint text,
  api_key_required boolean DEFAULT false,
  update_frequency text DEFAULT 'monthly'::text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT data_sources_pkey PRIMARY KEY (id)
);
CREATE TABLE public.data_versions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  table_name text NOT NULL,
  record_id uuid NOT NULL,
  version_number integer NOT NULL,
  data_snapshot jsonb NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  sync_id uuid,
  change_type text NOT NULL DEFAULT 'update'::text,
  CONSTRAINT data_versions_pkey PRIMARY KEY (id),
  CONSTRAINT data_versions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.document_comments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  document_id uuid NOT NULL,
  user_id uuid NOT NULL,
  user_name text NOT NULL,
  comment text NOT NULL,
  section text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT document_comments_pkey PRIMARY KEY (id),
  CONSTRAINT document_comments_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(id)
);
CREATE TABLE public.document_versions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  document_id uuid NOT NULL,
  version text NOT NULL,
  file_url text NOT NULL,
  file_name text NOT NULL,
  file_size bigint NOT NULL,
  changes_summary text NOT NULL,
  uploaded_at timestamp with time zone NOT NULL DEFAULT now(),
  uploaded_by uuid NOT NULL,
  CONSTRAINT document_versions_pkey PRIMARY KEY (id),
  CONSTRAINT document_versions_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(id)
);
CREATE TABLE public.documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  file_url text,
  file_name text,
  file_size bigint,
  mime_type text,
  document_type USER-DEFINED NOT NULL DEFAULT 'autre'::document_type,
  country text,
  tags ARRAY,
  uploaded_by uuid NOT NULL,
  is_public boolean NOT NULL DEFAULT true,
  download_count integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  view_count integer DEFAULT 0,
  featured boolean DEFAULT false,
  access_level text NOT NULL DEFAULT 'public'::text,
  allowed_roles ARRAY DEFAULT '{}'::text[],
  CONSTRAINT documents_pkey PRIMARY KEY (id),
  CONSTRAINT documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id)
);
CREATE TABLE public.encryption_keys (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  key_id text NOT NULL UNIQUE,
  algorithm text NOT NULL DEFAULT 'AES-256-GCM'::text,
  key_data text NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone,
  last_used timestamp with time zone,
  CONSTRAINT encryption_keys_pkey PRIMARY KEY (id),
  CONSTRAINT encryption_keys_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.event_registrations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL,
  user_id uuid NOT NULL,
  registered_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT event_registrations_pkey PRIMARY KEY (id),
  CONSTRAINT event_registrations_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT event_registrations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  start_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone NOT NULL,
  location text,
  is_virtual boolean NOT NULL DEFAULT false,
  virtual_link text,
  max_attendees integer,
  current_attendees integer NOT NULL DEFAULT 0,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT events_pkey PRIMARY KEY (id),
  CONSTRAINT events_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.focal_conversation_participants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid,
  focal_point_id uuid,
  user_id uuid,
  joined_at timestamp with time zone DEFAULT now(),
  last_read_at timestamp with time zone,
  is_muted boolean DEFAULT false,
  CONSTRAINT focal_conversation_participants_pkey PRIMARY KEY (id),
  CONSTRAINT focal_conversation_participants_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.focal_conversations(id),
  CONSTRAINT focal_conversation_participants_focal_point_id_fkey FOREIGN KEY (focal_point_id) REFERENCES public.focal_points(id),
  CONSTRAINT focal_conversation_participants_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.focal_conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  type text NOT NULL CHECK (type = ANY (ARRAY['country_team'::text, 'direct'::text, 'group'::text])),
  country_code text,
  name text,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT focal_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT focal_conversations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.focal_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid,
  sender_id uuid,
  sender_user_id uuid,
  content text NOT NULL,
  attachment_url text,
  attachment_type text,
  indicator_reference text,
  is_system_message boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  edited_at timestamp with time zone,
  CONSTRAINT focal_messages_pkey PRIMARY KEY (id),
  CONSTRAINT focal_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.focal_conversations(id),
  CONSTRAINT focal_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.focal_points(id),
  CONSTRAINT focal_messages_sender_user_id_fkey FOREIGN KEY (sender_user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.focal_point_invitations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  focal_point_id uuid NOT NULL,
  email text NOT NULL,
  token uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  sent_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '30 days'::interval),
  accepted_at timestamp with time zone,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'expired'::text, 'cancelled'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT focal_point_invitations_pkey PRIMARY KEY (id),
  CONSTRAINT focal_point_invitations_focal_point_id_fkey FOREIGN KEY (focal_point_id) REFERENCES public.focal_points(id)
);
CREATE TABLE public.focal_points (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  country_code text NOT NULL,
  designation_type text NOT NULL CHECK (designation_type = ANY (ARRAY['primary'::text, 'secondary'::text])),
  designated_by text,
  designation_document_url text,
  designation_date date DEFAULT CURRENT_DATE,
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text NOT NULL UNIQUE,
  phone text,
  whatsapp_number text,
  organization text,
  job_title text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'invited'::text, 'active'::text, 'suspended'::text, 'revoked'::text])),
  invitation_token uuid DEFAULT gen_random_uuid() UNIQUE,
  invitation_sent_at timestamp with time zone,
  invitation_expires_at timestamp with time zone,
  activated_at timestamp with time zone,
  expires_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT focal_points_pkey PRIMARY KEY (id),
  CONSTRAINT focal_points_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT focal_points_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.forum_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  color text DEFAULT '#3B82F6'::text,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT forum_categories_pkey PRIMARY KEY (id),
  CONSTRAINT forum_categories_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.forum_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  content text NOT NULL,
  category_id uuid NOT NULL,
  author_id uuid NOT NULL,
  is_pinned boolean NOT NULL DEFAULT false,
  is_locked boolean NOT NULL DEFAULT false,
  view_count integer NOT NULL DEFAULT 0,
  reply_count integer NOT NULL DEFAULT 0,
  last_reply_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT forum_posts_pkey PRIMARY KEY (id),
  CONSTRAINT forum_posts_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.forum_categories(id),
  CONSTRAINT forum_posts_author_id_fkey FOREIGN KEY (author_id) REFERENCES auth.users(id)
);
CREATE TABLE public.forum_replies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  content text NOT NULL,
  post_id uuid NOT NULL,
  author_id uuid NOT NULL,
  parent_reply_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT forum_replies_pkey PRIMARY KEY (id),
  CONSTRAINT forum_replies_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.forum_posts(id),
  CONSTRAINT forum_replies_author_id_fkey FOREIGN KEY (author_id) REFERENCES auth.users(id),
  CONSTRAINT forum_replies_parent_reply_id_fkey FOREIGN KEY (parent_reply_id) REFERENCES public.forum_replies(id)
);
CREATE TABLE public.homepage_content_blocks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  block_key text NOT NULL UNIQUE,
  content_fr jsonb DEFAULT '{}'::jsonb,
  content_en jsonb DEFAULT '{}'::jsonb,
  content_ar jsonb DEFAULT '{}'::jsonb,
  content_pt jsonb DEFAULT '{}'::jsonb,
  is_visible boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT homepage_content_blocks_pkey PRIMARY KEY (id),
  CONSTRAINT homepage_content_blocks_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.indicator_definitions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  unit text,
  category text,
  data_type text DEFAULT 'numeric'::text,
  calculation_method text,
  source_organization text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT indicator_definitions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.indicator_submissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  country_code text NOT NULL,
  indicator_code text NOT NULL,
  year integer NOT NULL,
  quarter integer CHECK (quarter = ANY (ARRAY[1, 2, 3, 4])),
  submitted_value numeric,
  value_text text,
  unit text,
  data_source text,
  methodology_notes text,
  submitted_by uuid NOT NULL,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'submitted'::text, 'validated'::text, 'rejected'::text, 'published'::text])),
  validated_by uuid,
  validation_date timestamp with time zone,
  validation_notes text,
  rejected_reason text,
  published_at timestamp with time zone,
  published_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT indicator_submissions_pkey PRIMARY KEY (id),
  CONSTRAINT indicator_submissions_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES public.profiles(id),
  CONSTRAINT indicator_submissions_validated_by_fkey FOREIGN KEY (validated_by) REFERENCES public.profiles(id),
  CONSTRAINT indicator_submissions_published_by_fkey FOREIGN KEY (published_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.indicator_translations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  indicator_code text NOT NULL,
  language_code text NOT NULL,
  display_name text NOT NULL,
  description text,
  category_name text,
  unit_display text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT indicator_translations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.languages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  native_name text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  is_default boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT languages_pkey PRIMARY KEY (id)
);
CREATE TABLE public.network_security_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['intrusion_attempt'::text, 'ddos_attack'::text, 'malware_detected'::text, 'suspicious_traffic'::text, 'firewall_breach'::text])),
  severity text NOT NULL CHECK (severity = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  source_ip inet,
  target_ip inet,
  description text NOT NULL,
  details jsonb,
  blocked boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  resolved boolean DEFAULT false,
  resolved_at timestamp with time zone,
  CONSTRAINT network_security_events_pkey PRIMARY KEY (id),
  CONSTRAINT network_security_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  type text NOT NULL DEFAULT 'info'::text,
  is_read boolean NOT NULL DEFAULT false,
  action_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.presentation_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id text NOT NULL UNIQUE,
  started_at timestamp with time zone DEFAULT now(),
  ended_at timestamp with time zone,
  total_duration integer,
  user_agent text,
  country text,
  sections_visited ARRAY,
  section_durations jsonb,
  interactions jsonb,
  completed boolean DEFAULT false,
  completion_rate numeric,
  device_type text,
  screen_resolution text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT presentation_sessions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  first_name text,
  last_name text,
  email text,
  role USER-DEFINED NOT NULL DEFAULT 'lecteur'::user_role,
  country text,
  organization text,
  avatar_url text,
  bio text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.security_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  two_factor_enabled boolean DEFAULT false,
  two_factor_secret text,
  backup_codes ARRAY,
  login_notifications boolean DEFAULT true,
  security_alerts boolean DEFAULT true,
  session_timeout integer DEFAULT 7200,
  max_concurrent_sessions integer DEFAULT 3,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  e2e_encryption_enabled boolean DEFAULT false,
  CONSTRAINT security_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT security_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.submissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  content text,
  status USER-DEFINED NOT NULL DEFAULT 'brouillon'::submission_status,
  submitted_by uuid NOT NULL,
  reviewed_by uuid,
  review_notes text,
  attachments jsonb DEFAULT '[]'::jsonb,
  submitted_at timestamp with time zone,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT submissions_pkey PRIMARY KEY (id),
  CONSTRAINT submissions_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES auth.users(id),
  CONSTRAINT submissions_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.sync_conflicts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agency_id uuid NOT NULL,
  table_name text NOT NULL,
  record_id uuid NOT NULL,
  source_data jsonb NOT NULL,
  target_data jsonb NOT NULL,
  conflict_type text NOT NULL,
  resolution_strategy text,
  resolved_data jsonb,
  resolved_at timestamp with time zone,
  resolved_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  is_resolved boolean NOT NULL DEFAULT false,
  CONSTRAINT sync_conflicts_pkey PRIMARY KEY (id),
  CONSTRAINT sync_conflicts_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES public.agencies(id),
  CONSTRAINT sync_conflicts_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.sync_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agency_id uuid NOT NULL,
  connector_id uuid,
  sync_type text NOT NULL CHECK (sync_type = ANY (ARRAY['full'::text, 'incremental'::text, 'manual'::text])),
  status text NOT NULL CHECK (status = ANY (ARRAY['started'::text, 'completed'::text, 'failed'::text, 'partial'::text])),
  records_processed integer DEFAULT 0,
  records_created integer DEFAULT 0,
  records_updated integer DEFAULT 0,
  records_failed integer DEFAULT 0,
  error_details jsonb,
  duration_ms integer,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT sync_logs_pkey PRIMARY KEY (id),
  CONSTRAINT sync_logs_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES public.agencies(id),
  CONSTRAINT sync_logs_connector_id_fkey FOREIGN KEY (connector_id) REFERENCES public.agency_connectors(id)
);
CREATE TABLE public.sync_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agency_id uuid NOT NULL,
  connector_id uuid NOT NULL,
  session_type text NOT NULL DEFAULT 'bidirectional'::text,
  status text NOT NULL DEFAULT 'active'::text,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  ended_at timestamp with time zone,
  records_processed integer DEFAULT 0,
  conflicts_detected integer DEFAULT 0,
  websocket_id text,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT sync_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT sync_sessions_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES public.agencies(id),
  CONSTRAINT sync_sessions_connector_id_fkey FOREIGN KEY (connector_id) REFERENCES public.agency_connectors(id)
);
CREATE TABLE public.sync_workflows (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agency_id uuid NOT NULL,
  workflow_name text NOT NULL,
  description text,
  steps jsonb NOT NULL DEFAULT '[]'::jsonb,
  conditions jsonb DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT sync_workflows_pkey PRIMARY KEY (id),
  CONSTRAINT sync_workflows_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES public.agencies(id),
  CONSTRAINT sync_workflows_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.translation_namespaces (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT translation_namespaces_pkey PRIMARY KEY (id)
);
CREATE TABLE public.translations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  language_id uuid NOT NULL,
  namespace_id uuid NOT NULL,
  key text NOT NULL,
  value text NOT NULL,
  context text,
  version integer NOT NULL DEFAULT 1,
  is_approved boolean NOT NULL DEFAULT false,
  created_by uuid,
  approved_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT translations_pkey PRIMARY KEY (id),
  CONSTRAINT translations_language_id_fkey FOREIGN KEY (language_id) REFERENCES public.languages(id),
  CONSTRAINT translations_namespace_id_fkey FOREIGN KEY (namespace_id) REFERENCES public.translation_namespaces(id),
  CONSTRAINT translations_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT translations_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.universal_service_indicators (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  indicator_code text NOT NULL,
  indicator_name text NOT NULL,
  value numeric,
  unit text,
  country_code text,
  region text,
  year integer NOT NULL,
  quarter integer,
  data_source text NOT NULL,
  source_url text,
  last_updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT universal_service_indicators_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  preferences jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT user_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  session_token text NOT NULL UNIQUE,
  ip_address inet,
  user_agent text,
  location text,
  is_active boolean DEFAULT true,
  last_activity timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.webauthn_credentials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  credential_id text NOT NULL UNIQUE,
  public_key text NOT NULL,
  name text NOT NULL,
  device_type text DEFAULT 'security_key'::text CHECK (device_type = ANY (ARRAY['biometric'::text, 'security_key'::text, 'platform'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  last_used timestamp with time zone,
  is_active boolean DEFAULT true,
  CONSTRAINT webauthn_credentials_pkey PRIMARY KEY (id),
  CONSTRAINT webauthn_credentials_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);