// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wsbawdvqfbmtjtdtyddy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzYmF3ZHZxZmJtdGp0ZHR5ZGR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2Nzk5OTksImV4cCI6MjA2ODI1NTk5OX0.vbVpqDkSDYHRQaDxpCV5UHlkdZmJqlTDXWccNe2CwIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});